# Builds docs for every release and pushes
# the updates gh-pages branch
# -> New docs on github-pages
name: build-docs

on:
  release:
    types: 
      - published

# no permissions to the token at global level
permissions: {} 
    
# ------------------------------------
# Jobs to run as part of this workflow
# ------------------------------------
jobs:
# -----------------------------------------
# Build the html and create gh-pages branch
# -----------------------------------------
  build_package:
    name: Build package on ubuntu-latest
    runs-on: ubuntu-latest
    # we need to create a branch, hence write
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.10"

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip
          pip install .[docs]

      - name: Build pages
        run: |
          cd docs
          make html

      - name: create gh-pages branch
        run: |
          pip install ghp-import
          ghp-import -n -p -f docs/build/html
